feat: david/prospective tenants invites
dijistanley/realhaus-sdk pull request #19
Opened 2023-01-15 09:00 UTC by Md-coder

created propectiveTenants.ts file

2023-01-29 18:17 UTC, nomadyus submitted a review, later dismissed

2023-01-31 03:54 UTC, dijistanley requested changes
You did not update the version for package.json

2023-02-04 19:24 UTC, nomadyus approved these changes

2023-02-05 16:02 UTC, dijistanley approved these changes

2023-02-05 16:02 UTC, merged